### ISSUE TITLE
02-asset-catalogue-alternate-icons doesn't work in TestFlight

### ISSUE THREAD

**Issue by twodayslate** [SwiftyAlex/Samples#1]
The asset doesn't appear in TestFlight and I assume an official release as well. This is probably an Apple bug. Not sure if it is a regression or you got it working in a release. I tested in Xcode version 14.0.1 (14A400)

https://github.com/gianpispi/icony is another example that uses a thumbnail approach

**Comment by SwiftyAlex** [comment]
Yeah, it looks like they seem to get stripped out when you upload the build 🤔 

I follow the thumb approach like you do in my own [app](https://apps.apple.com/gb/app/coffee-book/id1512681263).

I'll update the sample & article as soon as I can 😄

**Comment by SwiftyAlex** [comment]
The [article](https://www.alexanderlogan.co.uk/quicktip/02-asset-catalogue-alternate-icons/) has been updated, and the [sample](https://github.com/SwiftyAlex/Samples/commit/132e0d1c65630f9caf2f2ab259331e9c4cd8b1e2) too!

Thanks for spotting! 🎉

**Comment by twodayslate** [comment]
FB11699607
